source = $HOME/.config/hypr/mocha.conf
$accent = $blue
$accentAlpha = $blueAlpha
$font = JetBrainsMono Nerd Font

# GENERAL
general {
  hide_cursor = false
  grace = 2
}

# BACKGROUND
background {
  monitor =
  path = $HOME/Pictures/yourwallpaper.png
  blur_passes = 3
  brightness = 0.5
}

# WEATHER (top left)
label {
  monitor =
  text = cmd[update:600000] $HOME/.config/hypr/scripts/weather.sh
  color = $text
  font_size = 14
  font_family = $font
  position = 30, -30
  halign = left
  valign = top
}

# CLOCK — single label, pango colored via script
# HH blue : blue MM white : dim SS green
label {
  monitor =
  text = cmd[update:1000] $HOME/.config/hypr/scripts/clock.sh
  color = $text
  font_size = 90
  font_family = CommitMono Nerd Font
  position = -30, -20
  halign = right
  valign = top
}

# DATE — offset by font_size 90 height (~108px) + gap
label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $green
  font_size = 22
  font_family = CommitMono Nerd Font
  position = -30, -150
  halign = right
  valign = top
}

# USER AVATAR
image {
  monitor =
  path = $HOME/Pictures/yourpfp.png
  size = 110
  border_color = $blue
  border_size = 3
  rounding = -1
  position = 0, 75
  halign = center
  valign = center
}

# INPUT FIELD
input-field {
  monitor =
  size = 300, 60
  outline_thickness = 3
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = $blue
  inner_color = $surface0
  font_color = $text
  fade_on_empty = false
  placeholder_text = <span foreground="##$textAlpha"><i>󰌾 Logged in as </i><span foreground="##$blueAlpha">$USER</span></span>
  hide_input = false
  check_color = $green
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $yellow
  position = 0, -47
  halign = center
  valign = center
}


# EQUALIZER INVERTED
label {
  monitor =
  text = cmd[update:1] $HOME/.config/hypr/scripts/eq.sh
  color = $blue
  font_size = 15
  font_family = Noto Sans
  position = 0, 290
  halign = center
  valign = bottom
}

# NOW PLAYING
label {
  monitor =
  text = cmd[update:1] $HOME/.config/hypr/scripts/nowplaying.sh
  color = rgb(DCE0E8)
  font_size = 13
  font_family = $font
  position = 0, 260
  halign = center
  valign = bottom
}

# EQUALIZER NORMAL
label {
  monitor =
  text = cmd[update:1] $HOME/.config/hypr/scripts/eq_inverted.sh
  color = $blue
  font_size = 15
  font_family = Noto Sans
  position = 0, 240
  halign = center
  valign = bottom
}
